version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily  
    groups:
      actions-minor:
        update-types:
          - minor
          - patch

  - package-ecosystem: bun  
    directory: /
    schedule:
      interval: daily  # 每天更新
    groups:
      bun-development:  
        dependency-type: development
        update-types:
          - minor
          - patch
      bun-production:  
        dependency-type: production
        update-types:
          - patch
